### ISSUE TITLE
Table 'piper.users' doesn't exist

### ISSUE THREAD

**Issue by Rainmen-xia** [fireyy/piper#7]
where is this 'users' table?

**Comment by Rainmen-xia** [comment]
hello？

**Comment by fireyy** [comment]
Did you create a database named piper?

**Comment by Rainmen-xia** [comment]
yes

**Comment by Rainmen-xia** [comment]
但是我没有配置7牛那些

**Comment by Rainmen-xia** [comment]
应该没影响吧？

**Comment by Rainmen-xia** [comment]
应该没影响吧？

**Comment by fireyy** [comment]
你可以给一下详细的报错信息，或者截图也可以

**Comment by Rainmen-xia** [comment]
好的，稍等

**Comment by Rainmen-xia** [comment]
`

mysql> use piper
Reading table information for completion of table and column names
You can turn off this feature to get a quicker startup with -A

Database changed
`
刚才重跑了下npm run db那个命令又没报错了。。

但是run dev时报错了：

`
> node index.js

module.js:487
    throw err;
    ^

Error: Cannot find module 'koa-convert'

`

**Comment by Rainmen-xia** [comment]
安装koa-convert之后又报错了：
`。。。/piper/node_modules/passport-github/node_modules/passport-oauth2/lib/strategy.js:82
  if (!options.clientID) { throw new TypeError('OAuth2Strategy requires a clientID option'); 
`

**Comment by fireyy** [comment]
首次安装用户，无需执行 `npm run db`
其次，用户系统接入了 Github OAuth, 你需要在 [Github OAuth applications](https://github.com/settings/developers) 页面创建一个应用，拿到 `Client ID` 和 `Client Secret`, 填写到 `.env`

```
GITHUB_CLIENT_ID=你的 Client ID
GITHUB_CLIENT_SECRET=你的 Client Secret
```

**Comment by Rainmen-xia** [comment]
哦哦，果然。建立把那个首次安装不需要标明一下哦。现在run dev是跑起来了，但是直接访问提示
`{"name":"NOT_LOGIN","message":"not login"}`

**Comment by Rainmen-xia** [comment]
还有一个错误应该是前端少了一个字体包？
`
ERROR  Failed to compile with 1 errors                                                                                                                                                                                                                               10:38:10

 error  in ./~/element-ui/lib/theme-default/fonts/element-icons.ttf?t=1472440741

`

**Comment by fireyy** [comment]
没有登录的话会默认跳转到 登录页面的，你的页面地址看看是什么

**Comment by fireyy** [comment]
这个应该是 `element-ui` 的问题，你把具体的错误信息都放上来

**Comment by Rainmen-xia** [comment]
http://119.28.76.106:4000/index.html

**Comment by Rainmen-xia** [comment]
`

 ERROR  Failed to compile with 1 errors                                                                                                                                                                                                                               10:38:10

 error  in ./~/element-ui/lib/theme-default/fonts/element-icons.ttf?t=1472440741

Syntax Error: Unexpected end of JSON input
    at JSON.parse (<anonymous>)


 @ ./~/css-loader?{"minimize":false,"sourceMap":false}!./~/element-ui/lib/theme-default/index.css 6:775-824
 @ ./~/element-ui/lib/theme-default/index.css
 @ ./src/app.js
 @ multi ./build/dev-client ./src/app.js

`

**Comment by Rainmen-xia** [comment]
能帮我看下为啥无法登陆吗？

**Comment by fireyy** [comment]
`npm run dev` 是开发模式，如果是线上部署，需要运行

```
npm run build
```

然后

```
nom run start
```

**Comment by Rainmen-xia** [comment]
rum build 报错
`
7 verbose argv "/usr/local/bin/node" "/usr/local/bin/npm" "run" "build"
18 verbose node v8.2.0
19 verbose npm  v5.3.0
20 error code ELIFECYCLE
21 error errno 137
22 error piper@1.0.5 build: `npm run build:client && npm run build:server`
22 error Exit status 137
23 error Failed at the piper@1.0.5 build script.
23 error This is probably not a problem with npm. There is likely additional logging output above.
24 verbose exit [ 137, true ]

`

是我的node版本太高了？

**Comment by fireyy** [comment]
多一些错误信息，这部分看不出来

**Comment by Rainmen-xia** [comment]
我sudo了一下看起来貌似可以了，但是运行了一半还是报错了：
`
> piper@1.0.5 build /data/dev/piper
> npm run build:client && npm run build:server


> piper@1.0.5 build:client /data/dev/piper
> webpack --config build/webpack.prod.conf.js


Starting to optimize CSS...
Hash: 232d9b45ac7ec9ea1421
Version: webpack 2.7.0
Time: 37446ms
                                         Asset       Size  Chunks                    Chunk Names
       static/js/0.fa6ecd2ff3e31e0f155e.js.map    1.36 MB       0  [emitted]         
           static/js/0.fa6ecd2ff3e31e0f155e.js     199 kB       0  [emitted]         
           static/js/2.6df28aafb4aa896b30ac.js    34.1 kB       2  [emitted]         
           static/js/3.f73bc9a04ad78bbc51ae.js    29.6 kB       3  [emitted]         
           static/js/4.9131b229dd6e8366b7e9.js    33.2 kB       4  [emitted]         
           static/js/5.7fe2f50303da7fdf660b.js    30.4 kB       5  [emitted]         
           static/js/6.39337486319eace4d9c8.js    30.8 kB       6  [emitted]         
           static/js/7.50abaa4baa9493eac53c.js    34.2 kB       7  [emitted]         
      static/js/vendor.32d714306af8f876e88c.js     765 kB       8  [emitted]  [big]  vendor
         static/js/app.fbbde6324634322498ad.js    16.3 kB       9  [emitted]         app
    static/js/manifest.d887c37c8adabbbc963f.js    1.71 kB      10  [emitted]         manifest
           static/js/1.883e6c882c8a26d1ea1d.js    36.4 kB       1  [emitted]         
       static/js/1.883e6c882c8a26d1ea1d.js.map     271 kB       1  [emitted]         
       static/js/2.6df28aafb4aa896b30ac.js.map     253 kB       2  [emitted]         
       static/js/3.f73bc9a04ad78bbc51ae.js.map     230 kB       3  [emitted]         
       static/js/4.9131b229dd6e8366b7e9.js.map     246 kB       4  [emitted]         
       static/js/5.7fe2f50303da7fdf660b.js.map     233 kB       5  [emitted]         
       static/js/6.39337486319eace4d9c8.js.map     238 kB       6  [emitted]         
       static/js/7.50abaa4baa9493eac53c.js.map     207 kB       7  [emitted]         
  static/js/vendor.32d714306af8f876e88c.js.map    5.34 MB       8  [emitted]         vendor
     static/js/app.fbbde6324634322498ad.js.map    86.2 kB       9  [emitted]         app
static/js/manifest.d887c37c8adabbbc963f.js.map    15.2 kB      10  [emitted]         manifest
                                    index.html  561 bytes          [emitted]         
   [2] ./~/vue/dist/vue.esm.js 267 kB {8} [built]
  [21] ./~/element-ui/lib/utils/merge.js 396 bytes {8} [built]
  [22] ./~/element-ui/lib/utils/resize-event.js 7.18 kB {8} [built]
  [23] ./~/element-ui/lib/utils/scrollbar-width.js 990 bytes {8} [built]
  [24] ./~/element-ui/lib/utils/vue-popper.js 5.4 kB {8} [built]
  [25] ./src/router/index.js 1.63 kB {9} [built]
  [26] ./~/babel-runtime/core-js/object/keys.js 92 bytes {8} [built]
  [34] ./src/store/index.js 797 bytes {9} [built]
  [35] ./~/element-ui/lib/element-ui.common.js 678 kB {8} [built]
  [38] ./src/filters/index.js 499 bytes {9} [built]
  [50] ./~/element-ui/lib/theme-default/index.css 2.52 kB {9} [built] [failed] [1 error]
  [51] ./src/App.vue 1.54 kB {9} [built]
  [53] ./~/vuex-router-sync/index.js 1.37 kB {8} [built]
  [95] ./src/app.js 1.92 kB {9} [built]
 [160] ./src/views/Preview.vue 1.62 kB {7} [built]
    + 401 hidden modules

ERROR in ./~/element-ui/lib/theme-default/fonts/element-icons.ttf?t=1472440741
Module build failed: SyntaxError: Error parsing /data/dev/piper/node_modules/file-loader/node_modules/loader-utils/node_modules/json5/package.json: Unexpected end of input
    at Object.parse (native)
    at readPackage (module.js:81:52)
    at tryPackage (module.js:91:13)
    at Function.Module._findPath (module.js:153:20)
    at Function.Module._resolveFilename (module.js:323:25)
    at Function.Module._load (module.js:276:25)
    at Module.require (module.js:353:17)
    at require (internal/module.js:12:17)
    at Object.<anonymous> (/data/dev/piper/node_modules/file-loader/node_modules/loader-utils/lib/parseQuery.js:3:15)
    at Module._compile (module.js:409:26)
    at Object.Module._extensions..js (module.js:416:10)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Module.require (module.js:353:17)
    at require (internal/module.js:12:17)
    at Object.<anonymous> (/data/dev/piper/node_modules/file-loader/node_modules/loader-utils/lib/getOptions.js:3:20)
    at Module._compile (module.js:409:26)
    at Object.Module._extensions..js (module.js:416:10)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Module.require (module.js:353:17)
    at require (internal/module.js:12:17)
    at Object.<anonymous> (/data/dev/piper/node_modules/file-loader/node_modules/loader-utils/lib/index.js:3:20)
    at Module._compile (module.js:409:26)
    at Object.Module._extensions..js (module.js:416:10)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Module.require (module.js:353:17)
    at require (internal/module.js:12:17)
    at Object.<anonymous> (/data/dev/piper/node_modules/file-loader/index.js:5:19)
 @ ./~/css-loader?{"minimize":false,"sourceMap":true}!./~/element-ui/lib/theme-default/index.css 6:775-824
 @ ./~/element-ui/lib/theme-default/index.css
 @ ./src/app.js

ERROR in ./~/element-ui/lib/theme-default/index.css
Module build failed: ModuleBuildError: Module build failed: SyntaxError: Error parsing /data/dev/piper/node_modules/file-loader/node_modules/loader-utils/node_modules/json5/package.json: Unexpected end of input
    at Object.parse (native)
    at readPackage (module.js:81:52)
    at tryPackage (module.js:91:13)
    at Function.Module._findPath (module.js:153:20)
    at Function.Module._resolveFilename (module.js:323:25)
    at Function.Module._load (module.js:276:25)
    at Module.require (module.js:353:17)
    at require (internal/module.js:12:17)
    at Object.<anonymous> (/data/dev/piper/node_modules/file-loader/node_modules/loader-utils/lib/parseQuery.js:3:15)
    at Module._compile (module.js:409:26)
    at Object.Module._extensions..js (module.js:416:10)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Module.require (module.js:353:17)
    at require (internal/module.js:12:17)
    at Object.<anonymous> (/data/dev/piper/node_modules/file-loader/node_modules/loader-utils/lib/getOptions.js:3:20)
    at Module._compile (module.js:409:26)
    at Object.Module._extensions..js (module.js:416:10)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Module.require (module.js:353:17)
    at require (internal/module.js:12:17)
    at Object.<anonymous> (/data/dev/piper/node_modules/file-loader/node_modules/loader-utils/lib/index.js:3:20)
    at Module._compile (module.js:409:26)
    at Object.Module._extensions..js (module.js:416:10)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Module.require (module.js:353:17)
    at require (internal/module.js:12:17)
    at Object.<anonymous> (/data/dev/piper/node_modules/file-loader/index.js:5:19)
    at /data/dev/piper/node_modules/webpack/lib/NormalModule.js:192:19
    at /data/dev/piper/node_modules/loader-runner/lib/LoaderRunner.js:364:11
    at /data/dev/piper/node_modules/loader-runner/lib/LoaderRunner.js:230:18
    at runSyncOrAsync (/data/dev/piper/node_modules/loader-runner/lib/LoaderRunner.js:143:3)
    at iterateNormalLoaders (/data/dev/piper/node_modules/loader-runner/lib/LoaderRunner.js:229:2)
    at /data/dev/piper/node_modules/loader-runner/lib/LoaderRunner.js:202:4
    at /data/dev/piper/node_modules/enhanced-resolve/lib/CachedInputFileSystem.js:62:14
    at nextTickCallbackWith0Args (node.js:420:9)
    at process._tickCallback (node.js:349:13)
Child html-webpack-plugin for "index.html":
       [0] ./~/lodash/lodash.js 540 kB {0} [built]
       [1] ./~/html-webpack-plugin/lib/loader.js!./index.html 745 bytes {0} [built]
       [2] (webpack)/buildin/global.js 509 bytes {0} [built]
       [3] (webpack)/buildin/module.js 517 bytes {0} [built]
Child extract-text-webpack-plugin:
       [0] ./~/css-loader/lib/css-base.js 2.19 kB {0} [built]
       [1] ./~/element-ui/lib/theme-default/fonts/element-icons.ttf?t=1472440741 1.8 kB {0} [built] [failed] [1 error]
       [2] ./~/element-ui/lib/theme-default/fonts/element-icons.woff?t=1472440741 10.7 kB {0} [built]
       [3] ./~/base64-js/index.js 3.47 kB {0} [built]
       [4] ./~/buffer/index.js 48.6 kB {0} [built]
       [5] ./~/buffer/~/isarray/index.js 132 bytes {0} [built]
       [6] ./~/css-loader?{"minimize":false,"sourceMap":true}!./~/element-ui/lib/theme-default/index.css 313 kB {0} [built]
       [7] ./~/ieee754/index.js 2.05 kB {0} [built]
       [8] (webpack)/buildin/global.js 509 bytes {0} [built]
    
    ERROR in ./~/element-ui/lib/theme-default/fonts/element-icons.ttf?t=1472440741
    Module build failed: SyntaxError: Error parsing /data/dev/piper/node_modules/file-loader/node_modules/loader-utils/node_modules/json5/package.json: Unexpected end of input
        at Object.parse (native)
        at readPackage (module.js:81:52)
        at tryPackage (module.js:91:13)
        at Function.Module._findPath (module.js:153:20)
        at Function.Module._resolveFilename (module.js:323:25)
        at Function.Module._load (module.js:276:25)
        at Module.require (module.js:353:17)
        at require (internal/module.js:12:17)
        at Object.<anonymous> (/data/dev/piper/node_modules/file-loader/node_modules/loader-utils/lib/parseQuery.js:3:15)
        at Module._compile (module.js:409:26)
        at Object.Module._extensions..js (module.js:416:10)
        at Module.load (module.js:343:32)
        at Function.Module._load (module.js:300:12)
        at Module.require (module.js:353:17)
        at require (internal/module.js:12:17)
        at Object.<anonymous> (/data/dev/piper/node_modules/file-loader/node_modules/loader-utils/lib/getOptions.js:3:20)
        at Module._compile (module.js:409:26)
        at Object.Module._extensions..js (module.js:416:10)
        at Module.load (module.js:343:32)
        at Function.Module._load (module.js:300:12)
        at Module.require (module.js:353:17)
        at require (internal/module.js:12:17)
        at Object.<anonymous> (/data/dev/piper/node_modules/file-loader/node_modules/loader-utils/lib/index.js:3:20)
        at Module._compile (module.js:409:26)
        at Object.Module._extensions..js (module.js:416:10)
        at Module.load (module.js:343:32)
        at Function.Module._load (module.js:300:12)
        at Module.require (module.js:353:17)
        at require (internal/module.js:12:17)
        at Object.<anonymous> (/data/dev/piper/node_modules/file-loader/index.js:5:19)
     @ ./~/css-loader?{"minimize":false,"sourceMap":true}!./~/element-ui/lib/theme-default/index.css 6:775-824
npm ERR! code ELIFECYCLE
npm ERR! errno 2
npm ERR! piper@1.0.5 build:client: `webpack --config build/webpack.prod.conf.js`
npm ERR! Exit status 2
npm ERR! 
npm ERR! Failed at the piper@1.0.5 build:client script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2017-07-21T04_35_05_012Z-debug.log
npm ERR! code ELIFECYCLE
npm ERR! errno 2
npm ERR! piper@1.0.5 build: `npm run build:client && npm run build:server`
npm ERR! Exit status 2
npm ERR! 
npm ERR! Failed at the piper@1.0.5 build script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2017-07-21T04_35_05_111Z-debug.log

`

**Comment by Rainmen-xia** [comment]
是不是我那台linux机器性能太差了。。

**Comment by fireyy** [comment]
看起来像是 element-ui 的问题，我本地试一下看看

2017年7月21日 +0800 12:43 Rainmen-xia <notifications@github.com>，写道：

**Comment by fireyy** [comment]
目前未发现是什么问题，我加了 Travis CI
- node 8 + npm 5.3.0 是没问题的
