### ISSUE TITLE
Application error & npm run dev throw error

### ISSUE THREAD

**Issue by curder** [fireyy/piper#8]
版本信息：
操作系统：MacOSX
node: v6.10.2
npm: 5.3.0

1. 使用github授权登录demo得到如下报错信息。

**Application error**
An error occurred in the application and your page could not be served. If you are the application owner, check your logs for details.

2. 本地按照文档运行 `npm run dev` 命令得到如下错误：

> 抱歉！我修改了本地的package.json文件内容，确实是因为装了很久的node都没装上（在MacOSX和Linux上都试了一样的错误）。安装上8.*版本的node依赖一大堆问题，所以我就修改了package.json文件对node版本的依赖。
```
  "engines": {
    "node": ">=6.6.0", // 原本是  >=7.6.0
    "npm": ">=3.0.0"
  },
```

```
0 info it worked if it ends with ok
1 verbose cli [ '/usr/local/bin/node', '/usr/local/bin/npm', 'run', 'server' ]
2 info using npm@5.3.0
3 info using node@v6.10.2
4 verbose run-script [ 'preserver', 'server', 'postserver' ]
5 info lifecycle piper@1.0.5~preserver: piper@1.0.5
6 info lifecycle piper@1.0.5~server: piper@1.0.5
7 verbose lifecycle piper@1.0.5~server: unsafe-perm in lifecycle true
8 verbose lifecycle piper@1.0.5~server: PATH: /usr/local/lib/node_modules/npm/bin/node-gyp-bin:/Users/luo/Sites/tmp/piper/node_modules/.bin:/usr/local/lib/node_modules/npm/bin/node-gyp-bin:/Users/luo/Sites/tmp/piper/node_modules/.bin:/Users/luo/.swiftenv/shims:/usr/local/sbin:/Users/luo/.composer/vendor/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin
9 verbose lifecycle piper@1.0.5~server: CWD: /Users/luo/Sites/tmp/piper
10 silly lifecycle piper@1.0.5~server: Args: [ '-c', 'node index.js' ]
11 silly lifecycle piper@1.0.5~server: Returned: code: 1  signal: null
12 info lifecycle piper@1.0.5~server: Failed to exec server script
13 verbose stack Error: piper@1.0.5 server: `node index.js`
13 verbose stack Exit status 1
13 verbose stack     at EventEmitter.<anonymous> (/usr/local/lib/node_modules/npm/lib/utils/lifecycle.js:289:16)
13 verbose stack     at emitTwo (events.js:106:13)
13 verbose stack     at EventEmitter.emit (events.js:191:7)
13 verbose stack     at ChildProcess.<anonymous> (/usr/local/lib/node_modules/npm/lib/utils/spawn.js:40:14)
13 verbose stack     at emitTwo (events.js:106:13)
13 verbose stack     at ChildProcess.emit (events.js:191:7)
13 verbose stack     at maybeClose (internal/child_process.js:886:16)
13 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:226:5)
14 verbose pkgid piper@1.0.5
15 verbose cwd /Users/luo/Sites/tmp/piper
16 verbose Darwin 16.7.0
17 verbose argv "/usr/local/bin/node" "/usr/local/bin/npm" "run" "server"
18 verbose node v6.10.2
19 verbose npm  v5.3.0
20 error code ELIFECYCLE
21 error errno 1
22 error piper@1.0.5 server: `node index.js`
22 error Exit status 1
23 error Failed at the piper@1.0.5 server script.
23 error This is probably not a problem with npm. There is likely additional logging output above.
24 verbose exit [ 1, true ]
```

希望楼主能给出一些解决思路或者办法。谢谢~

**Comment by fireyy** [comment]
log 似乎不太完整，可以提供一下完整的 error log 吗？

**Comment by curder** [comment]
你好，首先感谢你的回复。

上面的错误日志是npm打到错误日志里的信息。

今天我在公司又重新按照你提供的readme安装测试了一下。报如下错误：

```
☁  piper [dev] ⚡ npm run dev

> piper@1.0.5 dev /Users/luo/WebRoot/Github/piper
> nodemon --watch server --watch build --exec npm run server

[nodemon] 1.11.0
[nodemon] to restart at any time, enter `rs`
[nodemon] watching: /Users/luo/WebRoot/Github/piper/server/**/* /Users/luo/WebRoot/Github/piper/build/**/*
[nodemon] starting `npm run server`
npm WARN invalid config loglevel="notice"

> piper@1.0.5 server /Users/luo/WebRoot/Github/piper
> node index.js


To use this project, you must update following to modules:

  node: 6.10.2 should be >=7.6.0


npm ERR! Darwin 15.6.0
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "run" "server"
npm ERR! node v6.10.2
npm ERR! npm  v4.2.0
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! piper@1.0.5 server: `node index.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the piper@1.0.5 server script 'node index.js'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the piper package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node index.js
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs piper
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls piper
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/luo/.npm/_logs/2017-09-01T00_50_06_821Z-debug.log
[nodemon] app crashed - waiting for file changes before starting...
^C
☁  piper [dev] ⚡ brew search node
leafnode               llnode                 node ✔                 node-build             node@4                 node@6                 nodebrew               nodeenv                nodenv
caskroom/cask/node-profiler

If you meant "node" specifically:
It was migrated from caskroom/cask to homebrew/core.
```
其中 `/Users/luo/.npm/_logs/2017-09-01T00_50_06_821Z-debug.log` 中错误提示内容为：
```
☁  piper [dev] ⚡ cat /Users/luo/.npm/_logs/2017-09-01T01_02_18_801Z-debug.log
0 info it worked if it ends with ok
1 verbose cli [ '/usr/local/bin/node', '/usr/local/bin/npm', 'run', 'server' ]
2 info using npm@4.2.0
3 info using node@v6.10.2
4 warn invalid config loglevel="notice"
5 verbose run-script [ 'preserver', 'server', 'postserver' ]
6 info lifecycle piper@1.0.5~preserver: piper@1.0.5
7 silly lifecycle piper@1.0.5~preserver: no script for preserver, continuing
8 info lifecycle piper@1.0.5~server: piper@1.0.5
9 verbose lifecycle piper@1.0.5~server: unsafe-perm in lifecycle true
10 verbose lifecycle piper@1.0.5~server: PATH: /usr/local/lib/node_modules/npm/bin/node-gyp-bin:/Users/luo/WebRoot/Github/piper/node_modules/.bin:/usr/local/lib/node_modules/smart-npm/node_modules/npm/bin/node-gyp-bin:/Users/luo/WebRoot/Github/piper/node_modules/.bin:/usr/local/opt/openssl/bin:/Users/luo/.composer/vendor/bin:/Applications/MAMP/Library/bin:/usr/local/sbin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/opt/X11/bin
11 verbose lifecycle piper@1.0.5~server: CWD: /Users/luo/WebRoot/Github/piper
12 silly lifecycle piper@1.0.5~server: Args: [ '-c', 'node index.js' ]
13 silly lifecycle piper@1.0.5~server: Returned: code: 1  signal: null
14 info lifecycle piper@1.0.5~server: Failed to exec server script
15 verbose stack Error: piper@1.0.5 server: `node index.js`
15 verbose stack Exit status 1
15 verbose stack     at EventEmitter.<anonymous> (/usr/local/lib/node_modules/npm/lib/utils/lifecycle.js:279:16)
15 verbose stack     at emitTwo (events.js:106:13)
15 verbose stack     at EventEmitter.emit (events.js:191:7)
15 verbose stack     at ChildProcess.<anonymous> (/usr/local/lib/node_modules/npm/lib/utils/spawn.js:40:14)
15 verbose stack     at emitTwo (events.js:106:13)
15 verbose stack     at ChildProcess.emit (events.js:191:7)
15 verbose stack     at maybeClose (internal/child_process.js:886:16)
15 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:226:5)
16 verbose pkgid piper@1.0.5
17 verbose cwd /Users/luo/WebRoot/Github/piper
18 error Darwin 15.6.0
19 error argv "/usr/local/bin/node" "/usr/local/bin/npm" "run" "server"
20 error node v6.10.2
21 error npm  v4.2.0
22 error code ELIFECYCLE
23 error errno 1
24 error piper@1.0.5 server: `node index.js`
24 error Exit status 1
25 error Failed at the piper@1.0.5 server script 'node index.js'.
25 error Make sure you have the latest version of node.js and npm installed.
25 error If you do, this is most likely a problem with the piper package,
25 error not with npm itself.
25 error Tell the author that this fails on your system:
25 error     node index.js
25 error You can get information on how to open an issue for this project with:
25 error     npm bugs piper
25 error Or if that isn't available, you can get their info via:
25 error     npm owner ls piper
25 error There is likely additional logging output above.
26 verbose exit [ 1, true ]
```


可以看到是node的主版本不对了。

系统是MacOSX，本地使用brew命令安装的node版本，7的版本在node官网不好找啊。

**请问能使用node的6.10.2版本跑动项目吗？**

如果实在不行，我得在虚拟机上安装一个更高版本的node来测试这个项目了，或者将项目依赖的组建移除和部分代码的删减使其能在 6.* 版本下跑动。

**Comment by fireyy** [comment]
因为项目里大量使用了 `await/async`, 没有做fallback处理，因此必须 node > 7.6.0 版本，MacOS 你可以使用这个安装包 [node-v7.6.0](https://nodejs.org/download/release/v7.6.0/node-v7.6.0.pkg)

**Comment by curder** [comment]
非常感谢，安装好你上面给的这个node包，我看到了不同的错误日志。让我去配置，我想我可以先自己动手配置Github授权。

```
☁  piper [dev] ⚡ npm run dev

> piper@1.0.5 dev /Users/luo/WebRoot/Github/piper
> nodemon --watch server --watch build --exec npm run server

[nodemon] 1.11.0
[nodemon] to restart at any time, enter `rs`
[nodemon] watching: /Users/luo/WebRoot/Github/piper/server/**/* /Users/luo/WebRoot/Github/piper/build/**/*
[nodemon] starting `npm run server`
npm WARN invalid config loglevel="notice"

> piper@1.0.5 server /Users/luo/WebRoot/Github/piper
> node index.js

/Users/luo/WebRoot/Github/piper/node_modules/passport-oauth2/lib/strategy.js:82
  if (!options.clientID) { throw new TypeError('OAuth2Strategy requires a clientID option'); }
                           ^

TypeError: OAuth2Strategy requires a clientID option
    at Strategy.OAuth2Strategy (/Users/luo/WebRoot/Github/piper/node_modules/passport-oauth2/lib/strategy.js:82:34)
    at new Strategy (/Users/luo/WebRoot/Github/piper/node_modules/passport-github/lib/strategy.js:62:18)
    at Object.<anonymous> (/Users/luo/WebRoot/Github/piper/server/lib/passport.js:19:14)
    at Module._compile (module.js:571:32)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
    at Module.require (module.js:498:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/Users/luo/WebRoot/Github/piper/server/index.js:49:1)
    at Module._compile (module.js:571:32)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
    at Module.require (module.js:498:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/Users/luo/WebRoot/Github/piper/index.js:8:13)
    at Module._compile (module.js:571:32)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:488:32)

npm ERR! Darwin 15.6.0
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "run" "server"
npm ERR! node v7.6.0
npm ERR! npm  v4.1.2
npm ERR! code ELIFECYCLE
npm ERR! piper@1.0.5 server: `node index.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the piper@1.0.5 server script 'node index.js'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the piper package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node index.js
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs piper
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls piper
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/luo/WebRoot/Github/piper/npm-debug.log
[nodemon] app crashed - waiting for file changes before starting...
^C
☁  piper [dev] ⚡
```

**Comment by fireyy** [comment]
👍

**Comment by curder** [comment]
非常感谢，刚刚测试了一下。很多功能还有待完善，构建一个简单的页面都还缺少很多元素，我是做后台开发的，想用这种拖拽式的方式制作简单的专题页面，包括一些常见的图片、文本、注册表单和导航等增删改功能。

最后，非常感谢提供的实现思路并且开源出来。

**Comment by fireyy** [comment]
对的，项目的思路就是提供基础功能，至于页面组件，每个使用者／公司的需求都不一样，这跟业务相关，因此这些需要使用者自己来定制的
